### ISSUE TITLE
Add more DevEx features to zilla-examples

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla-examples#59]
enhancements to make:
- [x] shorter path to external Kafka usage
- [x] downloadable artifacts per folder
- [x] wget/curl entry points to run examples
- [x] docker compose examples

housekeeping:
- [x] update to use new port 7114
- [x] normalize binding names

## Tested
- [x] amqp.reflect/
  - [x] error on main https://github.com/aklivity/zilla-examples/issues/84
- [x] grpc.echo/
- [x] grpc.kafka.echo/
- [x] grpc.kafka.fanout/
  - [x] error on main https://github.com/aklivity/zilla-examples/issues/83
- [x] grpc.kafka.proxy/
  - [x] error on main https://github.com/aklivity/zilla-examples/issues/85 
- [x] grpc.proxy/
- [x] http.echo.jwt/
  - [x] error on main https://github.com/aklivity/zilla-examples/issues/91
- [x] http.echo/
- [x] http.filesystem.config.server/
- [x] http.filesystem/
  - [x] error on main https://github.com/aklivity/zilla-examples/issues/90
- [x] http.kafka.async/
- [x] http.kafka.cache/
- [x] http.kafka.crud/
- [x] http.kafka.oneway/
- [x] http.kafka.sasl.scram/
- [x] http.kafka.sync/
- [x] http.proxy/
- [x] http.redpanda.sasl.scram/
- [x] kafka.broker/
- [x] kubernetes.prometheus.autoscale/
- [x] mqtt.kafka.broker.jwt/
  - [x] error on main https://github.com/aklivity/zilla-examples/issues/91
- [x] mqtt.kafka.broker/
- [x] mqtt.proxy.asyncapi/
- [x] quickstart/
- [x] sse.kafka.fanout/
- [x] sse.proxy.jwt/
  - [x] error on main https://github.com/aklivity/zilla-examples/issues/92
  - [x] error on main https://github.com/aklivity/zilla-examples/issues/91
- [x] tcp.echo/
- [x] tcp.reflect/
- [x] tls.echo/
- [x] tls.reflect/
- [x] ws.echo/
- [x] ws.reflect/

**Comment by vordimous** [comment]
cp example: https://docs.confluent.io/platform/current/platform-quickstart.html#quickstart
